# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(896, 588)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(10, 0, 871, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_clearLog = QtWidgets.QPushButton(Form)
        self.pushButton_clearLog.setGeometry(QtCore.QRect(710, 140, 61, 21))
        self.pushButton_clearLog.setObjectName("pushButton_clearLog")
        self.pushButton_pauseOperation = QtWidgets.QPushButton(Form)
        self.pushButton_pauseOperation.setGeometry(QtCore.QRect(780, 140, 91, 21))
        self.pushButton_pauseOperation.setObjectName("pushButton_pauseOperation")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 150, 881, 431))
        self.tabWidget.setObjectName("tabWidget")
        self.Home_tab = QtWidgets.QWidget()
        self.Home_tab.setObjectName("Home_tab")
        self.groupBox_7 = QtWidgets.QGroupBox(self.Home_tab)
        self.groupBox_7.setGeometry(QtCore.QRect(420, 150, 101, 81))
        self.groupBox_7.setObjectName("groupBox_7")
        self.tank_display_c = QtWidgets.QLCDNumber(self.groupBox_7)
        self.tank_display_c.setGeometry(QtCore.QRect(10, 20, 64, 23))
        self.tank_display_c.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.tank_display_c.setObjectName("tank_display_c")
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setGeometry(QtCore.QRect(80, 50, 21, 21))
        self.label_19.setObjectName("label_19")
        self.tank_display_f = QtWidgets.QLCDNumber(self.groupBox_7)
        self.tank_display_f.setGeometry(QtCore.QRect(10, 50, 64, 23))
        self.tank_display_f.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.tank_display_f.setObjectName("tank_display_f")
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setGeometry(QtCore.QRect(80, 20, 21, 21))
        self.label_20.setObjectName("label_20")
        self.tabWidget.addTab(self.Home_tab, "")
        self.Ratios_tab = QtWidgets.QWidget()
        self.Ratios_tab.setObjectName("Ratios_tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Ratios_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 881, 401))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 861, 77))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setGeometry(QtCore.QRect(160, 30, 62, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(450, 30, 62, 22))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(710, 30, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(90, 30, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(360, 30, 71, 20))
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(630, 30, 71, 20))
        self.label_8.setObjectName("label_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 180, 861, 77))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(70, 30, 71, 16))
        self.label_4.setObjectName("label_4")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(160, 30, 62, 22))
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(450, 30, 62, 22))
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(710, 30, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(340, 30, 91, 20))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(610, 30, 91, 20))
        self.label_9.setObjectName("label_9")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 270, 861, 77))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 131, 16))
        self.label_5.setObjectName("label_5")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(160, 30, 62, 22))
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(450, 30, 62, 22))
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(710, 30, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(290, 30, 141, 20))
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(550, 30, 151, 20))
        self.label_10.setObjectName("label_10")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 231, 80))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setGeometry(QtCore.QRect(80, 40, 71, 16))
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 10, 71, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(160, 40, 61, 20))
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.tabWidget.addTab(self.Ratios_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 861, 391))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_Co2_Pump = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_Co2_Pump.setObjectName("groupBox_Co2_Pump")
        self.label_11 = QtWidgets.QLabel(self.groupBox_Co2_Pump)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.label_11.setObjectName("label_11")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox_Co2_Pump)
        self.lcdNumber.setGeometry(QtCore.QRect(170, 20, 81, 23))
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_12 = QtWidgets.QLabel(self.groupBox_Co2_Pump)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.label_12.setObjectName("label_12")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.groupBox_Co2_Pump)
        self.lcdNumber_2.setGeometry(QtCore.QRect(170, 50, 81, 23))
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_Co2_Pump)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 80, 91, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.time_per_10_label = QtWidgets.QLabel(self.groupBox_Co2_Pump)
        self.time_per_10_label.setGeometry(QtCore.QRect(310, 50, 81, 21))
        self.time_per_10_label.setObjectName("time_per_10_label")
        self.time_per_10_label_2 = QtWidgets.QLabel(self.groupBox_Co2_Pump)
        self.time_per_10_label_2.setGeometry(QtCore.QRect(310, 20, 81, 21))
        self.time_per_10_label_2.setObjectName("time_per_10_label_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.groupBox_Co2_Pump)
        self.lcdNumber_3.setGeometry(QtCore.QRect(170, 110, 81, 23))
        self.lcdNumber_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_Co2_Pump)
        self.pushButton_5.setGeometry(QtCore.QRect(170, 80, 81, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_Co2_Pump)
        self.comboBox.setGeometry(QtCore.QRect(310, 80, 81, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.groupBox_Co2_Pump)
        self.lcdNumber_4.setGeometry(QtCore.QRect(170, 140, 81, 23))
        self.lcdNumber_4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.label_13 = QtWidgets.QLabel(self.groupBox_Co2_Pump)
        self.label_13.setGeometry(QtCore.QRect(10, 110, 91, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_Co2_Pump)
        self.label_14.setGeometry(QtCore.QRect(20, 141, 71, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_Co2_Pump)
        self.label_15.setGeometry(QtCore.QRect(310, 112, 47, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_Co2_Pump)
        self.label_16.setGeometry(QtCore.QRect(310, 142, 47, 21))
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.groupBox_Co2_Pump, 0, 0, 1, 1)
        self.groupBox_Water_Conditioner_Pump = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_Water_Conditioner_Pump.setObjectName("groupBox_Water_Conditioner_Pump")
        self.label_29 = QtWidgets.QLabel(self.groupBox_Water_Conditioner_Pump)
        self.label_29.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.label_29.setObjectName("label_29")
        self.lcdNumber_13 = QtWidgets.QLCDNumber(self.groupBox_Water_Conditioner_Pump)
        self.lcdNumber_13.setGeometry(QtCore.QRect(170, 20, 81, 23))
        self.lcdNumber_13.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.label_30 = QtWidgets.QLabel(self.groupBox_Water_Conditioner_Pump)
        self.label_30.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.label_30.setObjectName("label_30")
        self.lcdNumber_14 = QtWidgets.QLCDNumber(self.groupBox_Water_Conditioner_Pump)
        self.lcdNumber_14.setGeometry(QtCore.QRect(170, 50, 81, 23))
        self.lcdNumber_14.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_Water_Conditioner_Pump)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 80, 91, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.time_per_10_label_7 = QtWidgets.QLabel(self.groupBox_Water_Conditioner_Pump)
        self.time_per_10_label_7.setGeometry(QtCore.QRect(310, 50, 81, 21))
        self.time_per_10_label_7.setObjectName("time_per_10_label_7")
        self.time_per_10_label_8 = QtWidgets.QLabel(self.groupBox_Water_Conditioner_Pump)
        self.time_per_10_label_8.setGeometry(QtCore.QRect(310, 20, 81, 21))
        self.time_per_10_label_8.setObjectName("time_per_10_label_8")
        self.lcdNumber_15 = QtWidgets.QLCDNumber(self.groupBox_Water_Conditioner_Pump)
        self.lcdNumber_15.setGeometry(QtCore.QRect(170, 110, 81, 23))
        self.lcdNumber_15.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_Water_Conditioner_Pump)
        self.pushButton_11.setGeometry(QtCore.QRect(170, 80, 81, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_Water_Conditioner_Pump)
        self.comboBox_4.setGeometry(QtCore.QRect(310, 80, 81, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.lcdNumber_16 = QtWidgets.QLCDNumber(self.groupBox_Water_Conditioner_Pump)
        self.lcdNumber_16.setGeometry(QtCore.QRect(170, 140, 81, 23))
        self.lcdNumber_16.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.label_31 = QtWidgets.QLabel(self.groupBox_Water_Conditioner_Pump)
        self.label_31.setGeometry(QtCore.QRect(10, 110, 91, 20))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_Water_Conditioner_Pump)
        self.label_32.setGeometry(QtCore.QRect(20, 141, 71, 20))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_Water_Conditioner_Pump)
        self.label_33.setGeometry(QtCore.QRect(310, 112, 47, 21))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox_Water_Conditioner_Pump)
        self.label_34.setGeometry(QtCore.QRect(310, 142, 47, 21))
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.groupBox_Water_Conditioner_Pump, 1, 0, 1, 1)
        self.groupBox_Fertilizer_Pump = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_Fertilizer_Pump.setObjectName("groupBox_Fertilizer_Pump")
        self.label_23 = QtWidgets.QLabel(self.groupBox_Fertilizer_Pump)
        self.label_23.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.label_23.setObjectName("label_23")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.groupBox_Fertilizer_Pump)
        self.lcdNumber_9.setGeometry(QtCore.QRect(170, 20, 81, 23))
        self.lcdNumber_9.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.label_24 = QtWidgets.QLabel(self.groupBox_Fertilizer_Pump)
        self.label_24.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.label_24.setObjectName("label_24")
        self.lcdNumber_10 = QtWidgets.QLCDNumber(self.groupBox_Fertilizer_Pump)
        self.lcdNumber_10.setGeometry(QtCore.QRect(170, 50, 81, 23))
        self.lcdNumber_10.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_Fertilizer_Pump)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 80, 91, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.time_per_10_label_5 = QtWidgets.QLabel(self.groupBox_Fertilizer_Pump)
        self.time_per_10_label_5.setGeometry(QtCore.QRect(310, 50, 81, 21))
        self.time_per_10_label_5.setObjectName("time_per_10_label_5")
        self.time_per_10_label_6 = QtWidgets.QLabel(self.groupBox_Fertilizer_Pump)
        self.time_per_10_label_6.setGeometry(QtCore.QRect(310, 20, 81, 21))
        self.time_per_10_label_6.setObjectName("time_per_10_label_6")
        self.lcdNumber_11 = QtWidgets.QLCDNumber(self.groupBox_Fertilizer_Pump)
        self.lcdNumber_11.setGeometry(QtCore.QRect(170, 110, 81, 23))
        self.lcdNumber_11.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_Fertilizer_Pump)
        self.pushButton_9.setGeometry(QtCore.QRect(170, 80, 81, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_Fertilizer_Pump)
        self.comboBox_3.setGeometry(QtCore.QRect(310, 80, 81, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.lcdNumber_12 = QtWidgets.QLCDNumber(self.groupBox_Fertilizer_Pump)
        self.lcdNumber_12.setGeometry(QtCore.QRect(170, 140, 81, 23))
        self.lcdNumber_12.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.label_25 = QtWidgets.QLabel(self.groupBox_Fertilizer_Pump)
        self.label_25.setGeometry(QtCore.QRect(10, 110, 91, 20))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_Fertilizer_Pump)
        self.label_26.setGeometry(QtCore.QRect(20, 141, 71, 20))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_Fertilizer_Pump)
        self.label_27.setGeometry(QtCore.QRect(310, 112, 47, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_Fertilizer_Pump)
        self.label_28.setGeometry(QtCore.QRect(310, 142, 47, 21))
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.groupBox_Fertilizer_Pump, 0, 1, 1, 1)
        self.groupBox_Feeding_Motors = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_Feeding_Motors.setObjectName("groupBox_Feeding_Motors")
        self.label_Seconds = QtWidgets.QLabel(self.groupBox_Feeding_Motors)
        self.label_Seconds.setGeometry(QtCore.QRect(150, 40, 47, 21))
        self.label_Seconds.setObjectName("label_Seconds")
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.groupBox_Feeding_Motors)
        self.doubleSpinBox_8.setGeometry(QtCore.QRect(60, 40, 81, 22))
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.groupBox_Feeding_Motors)
        self.doubleSpinBox_9.setGeometry(QtCore.QRect(60, 90, 81, 22))
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.groupBox_Feeding_Motors)
        self.doubleSpinBox_10.setGeometry(QtCore.QRect(60, 140, 81, 22))
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.label_Seconds_2 = QtWidgets.QLabel(self.groupBox_Feeding_Motors)
        self.label_Seconds_2.setGeometry(QtCore.QRect(150, 90, 47, 21))
        self.label_Seconds_2.setObjectName("label_Seconds_2")
        self.label_Seconds_3 = QtWidgets.QLabel(self.groupBox_Feeding_Motors)
        self.label_Seconds_3.setGeometry(QtCore.QRect(150, 140, 47, 21))
        self.label_Seconds_3.setObjectName("label_Seconds_3")
        self.label_flakes = QtWidgets.QLabel(self.groupBox_Feeding_Motors)
        self.label_flakes.setGeometry(QtCore.QRect(10, 40, 41, 21))
        self.label_flakes.setObjectName("label_flakes")
        self.label_pellets = QtWidgets.QLabel(self.groupBox_Feeding_Motors)
        self.label_pellets.setGeometry(QtCore.QRect(10, 90, 41, 21))
        self.label_pellets.setObjectName("label_pellets")
        self.label_wafers = QtWidgets.QLabel(self.groupBox_Feeding_Motors)
        self.label_wafers.setGeometry(QtCore.QRect(10, 140, 41, 21))
        self.label_wafers.setObjectName("label_wafers")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_Feeding_Motors)
        self.pushButton.setGeometry(QtCore.QRect(280, 120, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.radioButton_flakes = QtWidgets.QRadioButton(self.groupBox_Feeding_Motors)
        self.radioButton_flakes.setGeometry(QtCore.QRect(210, 40, 82, 17))
        self.radioButton_flakes.setText("")
        self.radioButton_flakes.setObjectName("radioButton_flakes")
        self.radioButton_pellets = QtWidgets.QRadioButton(self.groupBox_Feeding_Motors)
        self.radioButton_pellets.setGeometry(QtCore.QRect(210, 90, 82, 17))
        self.radioButton_pellets.setText("")
        self.radioButton_pellets.setObjectName("radioButton_pellets")
        self.radioButton_wafers = QtWidgets.QRadioButton(self.groupBox_Feeding_Motors)
        self.radioButton_wafers.setGeometry(QtCore.QRect(210, 140, 82, 17))
        self.radioButton_wafers.setText("")
        self.radioButton_wafers.setObjectName("radioButton_wafers")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_Feeding_Motors)
        self.comboBox_5.setGeometry(QtCore.QRect(280, 60, 81, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout.addWidget(self.groupBox_Feeding_Motors, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_25 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_25.setGeometry(QtCore.QRect(440, 10, 431, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_25.sizePolicy().hasHeightForWidth())
        self.groupBox_25.setSizePolicy(sizePolicy)
        self.groupBox_25.setTitle("")
        self.groupBox_25.setObjectName("groupBox_25")
        self.groupBox_26 = QtWidgets.QGroupBox(self.groupBox_25)
        self.groupBox_26.setGeometry(QtCore.QRect(10, 0, 411, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_26.sizePolicy().hasHeightForWidth())
        self.groupBox_26.setSizePolicy(sizePolicy)
        self.groupBox_26.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_26.setObjectName("groupBox_26")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_26)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.hours_22 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_22.setCheckable(True)
        self.hours_22.setAutoDefault(True)
        self.hours_22.setObjectName("hours_22")
        self.gridLayout_5.addWidget(self.hours_22, 3, 5, 1, 1)
        self.hours_21 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_21.setCheckable(True)
        self.hours_21.setAutoDefault(True)
        self.hours_21.setObjectName("hours_21")
        self.gridLayout_5.addWidget(self.hours_21, 3, 4, 1, 1)
        self.hours_5 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_5.setCheckable(True)
        self.hours_5.setAutoDefault(True)
        self.hours_5.setObjectName("hours_5")
        self.gridLayout_5.addWidget(self.hours_5, 0, 6, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_26)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 0, 0, 1, 1)
        self.hours_0 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_0.setCheckable(True)
        self.hours_0.setAutoDefault(True)
        self.hours_0.setObjectName("hours_0")
        self.gridLayout_5.addWidget(self.hours_0, 0, 1, 1, 1)
        self.hours_20 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_20.setCheckable(True)
        self.hours_20.setAutoDefault(True)
        self.hours_20.setFlat(False)
        self.hours_20.setObjectName("hours_20")
        self.gridLayout_5.addWidget(self.hours_20, 3, 3, 1, 1)
        self.hours_1 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_1.setCheckable(True)
        self.hours_1.setAutoDefault(True)
        self.hours_1.setObjectName("hours_1")
        self.gridLayout_5.addWidget(self.hours_1, 0, 2, 1, 1)
        self.hours_23 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_23.setCheckable(True)
        self.hours_23.setAutoDefault(True)
        self.hours_23.setObjectName("hours_23")
        self.gridLayout_5.addWidget(self.hours_23, 3, 6, 1, 1)
        self.hours_14 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_14.setCheckable(True)
        self.hours_14.setAutoDefault(True)
        self.hours_14.setObjectName("hours_14")
        self.gridLayout_5.addWidget(self.hours_14, 2, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_26)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 2, 0, 1, 1)
        self.hours_10 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_10.setCheckable(True)
        self.hours_10.setAutoDefault(True)
        self.hours_10.setObjectName("hours_10")
        self.gridLayout_5.addWidget(self.hours_10, 1, 5, 1, 1)
        self.hours_18 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_18.setStyleSheet("")
        self.hours_18.setCheckable(True)
        self.hours_18.setAutoDefault(True)
        self.hours_18.setObjectName("hours_18")
        self.gridLayout_5.addWidget(self.hours_18, 3, 1, 1, 1)
        self.hours_3 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_3.setCheckable(True)
        self.hours_3.setAutoDefault(True)
        self.hours_3.setObjectName("hours_3")
        self.gridLayout_5.addWidget(self.hours_3, 0, 4, 1, 1)
        self.hours_16 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_16.setCheckable(True)
        self.hours_16.setAutoDefault(True)
        self.hours_16.setObjectName("hours_16")
        self.gridLayout_5.addWidget(self.hours_16, 2, 5, 1, 1)
        self.hours_9 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_9.setCheckable(True)
        self.hours_9.setAutoDefault(True)
        self.hours_9.setObjectName("hours_9")
        self.gridLayout_5.addWidget(self.hours_9, 1, 4, 1, 1)
        self.hours_7 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_7.setCheckable(True)
        self.hours_7.setAutoDefault(True)
        self.hours_7.setObjectName("hours_7")
        self.gridLayout_5.addWidget(self.hours_7, 1, 2, 1, 1)
        self.hours_11 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_11.setCheckable(True)
        self.hours_11.setAutoDefault(True)
        self.hours_11.setObjectName("hours_11")
        self.gridLayout_5.addWidget(self.hours_11, 1, 6, 1, 1)
        self.hours_13 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_13.setCheckable(True)
        self.hours_13.setAutoDefault(True)
        self.hours_13.setDefault(False)
        self.hours_13.setFlat(False)
        self.hours_13.setObjectName("hours_13")
        self.gridLayout_5.addWidget(self.hours_13, 2, 2, 1, 1)
        self.hours_6 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_6.setCheckable(True)
        self.hours_6.setAutoDefault(True)
        self.hours_6.setObjectName("hours_6")
        self.gridLayout_5.addWidget(self.hours_6, 1, 1, 1, 1)
        self.hours_12 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_12.setCheckable(True)
        self.hours_12.setAutoDefault(True)
        self.hours_12.setObjectName("hours_12")
        self.gridLayout_5.addWidget(self.hours_12, 2, 1, 1, 1)
        self.hours_8 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_8.setCheckable(True)
        self.hours_8.setAutoDefault(True)
        self.hours_8.setObjectName("hours_8")
        self.gridLayout_5.addWidget(self.hours_8, 1, 3, 1, 1)
        self.hours_2 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_2.setCheckable(True)
        self.hours_2.setAutoDefault(True)
        self.hours_2.setObjectName("hours_2")
        self.gridLayout_5.addWidget(self.hours_2, 0, 3, 1, 1)
        self.hours_17 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_17.setCheckable(True)
        self.hours_17.setAutoDefault(True)
        self.hours_17.setObjectName("hours_17")
        self.gridLayout_5.addWidget(self.hours_17, 2, 6, 1, 1)
        self.hours_15 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_15.setCheckable(True)
        self.hours_15.setAutoDefault(True)
        self.hours_15.setObjectName("hours_15")
        self.gridLayout_5.addWidget(self.hours_15, 2, 4, 1, 1)
        self.hours_4 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_4.setCheckable(True)
        self.hours_4.setAutoDefault(True)
        self.hours_4.setObjectName("hours_4")
        self.gridLayout_5.addWidget(self.hours_4, 0, 5, 1, 1)
        self.hours_19 = QtWidgets.QPushButton(self.groupBox_26)
        self.hours_19.setCheckable(True)
        self.hours_19.setAutoDefault(True)
        self.hours_19.setObjectName("hours_19")
        self.gridLayout_5.addWidget(self.hours_19, 3, 2, 1, 1)
        self.groupBox_27 = QtWidgets.QGroupBox(self.groupBox_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_27.sizePolicy().hasHeightForWidth())
        self.groupBox_27.setSizePolicy(sizePolicy)
        self.groupBox_27.setTitle("")
        self.groupBox_27.setFlat(False)
        self.groupBox_27.setObjectName("groupBox_27")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_27)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hour_comboBox = QtWidgets.QComboBox(self.groupBox_27)
        self.hour_comboBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.hour_comboBox.setObjectName("hour_comboBox")
        self.hour_comboBox.addItem("")
        self.hour_comboBox.addItem("")
        self.hour_comboBox.addItem("")
        self.hour_comboBox.addItem("")
        self.hour_comboBox.addItem("")
        self.hour_comboBox.addItem("")
        self.hour_comboBox.addItem("")
        self.hour_comboBox.addItem("")
        self.hour_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.hour_comboBox)
        self.hour_clear = QtWidgets.QPushButton(self.groupBox_27)
        self.hour_clear.setObjectName("hour_clear")
        self.horizontalLayout_2.addWidget(self.hour_clear)
        self.hour_save_button = QtWidgets.QPushButton(self.groupBox_27)
        self.hour_save_button.setObjectName("hour_save_button")
        self.horizontalLayout_2.addWidget(self.hour_save_button)
        self.gridLayout_5.addWidget(self.groupBox_27, 4, 0, 1, 7)
        self.groupBox_24 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_24.setGeometry(QtCore.QRect(0, 10, 431, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_24.sizePolicy().hasHeightForWidth())
        self.groupBox_24.setSizePolicy(sizePolicy)
        self.groupBox_24.setTitle("")
        self.groupBox_24.setObjectName("groupBox_24")
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(self.groupBox_24)
        self.calendarWidget_2.setGeometry(QtCore.QRect(10, 10, 411, 183))
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_clearLog.setText(_translate("Form", "Clear Log"))
        self.pushButton_pauseOperation.setText(_translate("Form", "Pause Operation"))
        self.groupBox_7.setTitle(_translate("Form", "Aquarium"))
        self.label_19.setText(_translate("Form", "° F"))
        self.label_20.setText(_translate("Form", "° C"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Home_tab), _translate("Form", "Home"))
        self.label_2.setText(_translate("Form", " Co2 Ratio"))
        self.label_3.setText(_translate("Form", "Co2 To Water"))
        self.label_8.setText(_translate("Form", "Co2 Dosage:"))
        self.label_4.setText(_translate("Form", "Fertilizer Ratio"))
        self.label_6.setText(_translate("Form", "Fertilizer To Water"))
        self.label_9.setText(_translate("Form", "Fertilizer Dosage:"))
        self.label_5.setText(_translate("Form", "Water Condiontioner Ratio"))
        self.label_7.setText(_translate("Form", " Water Conditioner To Water"))
        self.label_10.setText(_translate("Form", " Water Condiontioner Dosage:"))
        self.label.setText(_translate("Form", " Tank Size  (L)"))
        self.pushButton_3.setText(_translate("Form", "Save Ratios"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Ratios_tab), _translate("Form", "Ratios"))
        self.groupBox_Co2_Pump.setTitle(_translate("Form", "Co2 Pump:"))
        self.label_11.setText(_translate("Form", " Previous Calibration"))
        self.label_12.setText(_translate("Form", "New Calibration"))
        self.pushButton_4.setText(_translate("Form", "Calibrate Now"))
        self.time_per_10_label.setText(_translate("Form", "Time Per 10(mL)"))
        self.time_per_10_label_2.setText(_translate("Form", "Time Per 10(mL)"))
        self.pushButton_5.setText(_translate("Form", "Dose Now"))
        self.comboBox.setItemText(0, _translate("Form", "Auto"))
        self.comboBox.setItemText(1, _translate("Form", "Manual"))
        self.label_13.setText(_translate("Form", "Current Dose(mL)"))
        self.label_14.setText(_translate("Form", "Dose Runtime"))
        self.label_15.setText(_translate("Form", "(mL)"))
        self.label_16.setText(_translate("Form", "(Seconds)"))
        self.groupBox_Water_Conditioner_Pump.setTitle(_translate("Form", "Water Conditioner Pump:"))
        self.label_29.setText(_translate("Form", " Previous Calibration"))
        self.label_30.setText(_translate("Form", "New Calibration"))
        self.pushButton_10.setText(_translate("Form", "Calibrate Now"))
        self.time_per_10_label_7.setText(_translate("Form", "Time Per 10(mL)"))
        self.time_per_10_label_8.setText(_translate("Form", "Time Per 10(mL)"))
        self.pushButton_11.setText(_translate("Form", "Dose Now"))
        self.comboBox_4.setItemText(0, _translate("Form", "Auto"))
        self.comboBox_4.setItemText(1, _translate("Form", "Manual"))
        self.label_31.setText(_translate("Form", "Current Dose(mL)"))
        self.label_32.setText(_translate("Form", "Dose Runtime"))
        self.label_33.setText(_translate("Form", "(mL)"))
        self.label_34.setText(_translate("Form", "(Seconds)"))
        self.groupBox_Fertilizer_Pump.setTitle(_translate("Form", "Fertilzer Pump:"))
        self.label_23.setText(_translate("Form", " Previous Calibration"))
        self.label_24.setText(_translate("Form", "New Calibration"))
        self.pushButton_8.setText(_translate("Form", "Calibrate Now"))
        self.time_per_10_label_5.setText(_translate("Form", "Time Per 10(mL)"))
        self.time_per_10_label_6.setText(_translate("Form", "Time Per 10(mL)"))
        self.pushButton_9.setText(_translate("Form", "Dose Now"))
        self.comboBox_3.setItemText(0, _translate("Form", "Auto"))
        self.comboBox_3.setItemText(1, _translate("Form", "Manual"))
        self.label_25.setText(_translate("Form", "Current Dose(mL)"))
        self.label_26.setText(_translate("Form", "Dose Runtime"))
        self.label_27.setText(_translate("Form", "(mL)"))
        self.label_28.setText(_translate("Form", "(Seconds)"))
        self.groupBox_Feeding_Motors.setTitle(_translate("Form", "Feeding Motors"))
        self.label_Seconds.setText(_translate("Form", "(Seconds)"))
        self.label_Seconds_2.setText(_translate("Form", "(Seconds)"))
        self.label_Seconds_3.setText(_translate("Form", "(Seconds)"))
        self.label_flakes.setText(_translate("Form", "Flakes"))
        self.label_pellets.setText(_translate("Form", "Pellets"))
        self.label_wafers.setText(_translate("Form", "Wafers"))
        self.pushButton.setText(_translate("Form", "Feed Now"))
        self.comboBox_5.setItemText(0, _translate("Form", "Auto"))
        self.comboBox_5.setItemText(1, _translate("Form", "Manual"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Pumps"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Lights"))
        self.groupBox_26.setTitle(_translate("Form", "Hours"))
        self.hours_22.setText(_translate("Form", "22"))
        self.hours_21.setText(_translate("Form", "21"))
        self.hours_5.setText(_translate("Form", "5"))
        self.label_17.setText(_translate("Form", "AM:"))
        self.hours_0.setText(_translate("Form", "0"))
        self.hours_20.setText(_translate("Form", "20"))
        self.hours_1.setText(_translate("Form", "1"))
        self.hours_23.setText(_translate("Form", "23"))
        self.hours_14.setText(_translate("Form", "14"))
        self.label_18.setText(_translate("Form", "PM:"))
        self.hours_10.setText(_translate("Form", "10"))
        self.hours_18.setText(_translate("Form", "18"))
        self.hours_3.setText(_translate("Form", "3"))
        self.hours_16.setText(_translate("Form", "16"))
        self.hours_9.setText(_translate("Form", "9"))
        self.hours_7.setText(_translate("Form", "7"))
        self.hours_11.setText(_translate("Form", "11"))
        self.hours_13.setText(_translate("Form", "13"))
        self.hours_6.setText(_translate("Form", "6"))
        self.hours_12.setText(_translate("Form", "12"))
        self.hours_8.setText(_translate("Form", "8"))
        self.hours_2.setText(_translate("Form", "2"))
        self.hours_17.setText(_translate("Form", "17"))
        self.hours_15.setText(_translate("Form", "15"))
        self.hours_4.setText(_translate("Form", "4"))
        self.hours_19.setText(_translate("Form", "19"))
        self.hour_comboBox.setItemText(0, _translate("Form", "--- Day"))
        self.hour_comboBox.setItemText(1, _translate("Form", "--- Night"))
        self.hour_comboBox.setItemText(2, _translate("Form", "--- Off"))
        self.hour_comboBox.setItemText(3, _translate("Form", "Co2"))
        self.hour_comboBox.setItemText(4, _translate("Form", "Fertilizer"))
        self.hour_comboBox.setItemText(5, _translate("Form", "Water Conditioner"))
        self.hour_comboBox.setItemText(6, _translate("Form", "Flakes"))
        self.hour_comboBox.setItemText(7, _translate("Form", "Pellets"))
        self.hour_comboBox.setItemText(8, _translate("Form", "Wafers"))
        self.hour_clear.setText(_translate("Form", "Clear All"))
        self.hour_save_button.setText(_translate("Form", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Schedules"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Sys Settings"))
